// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreApp.Data.Concreate;

#nullable disable

namespace StoreAppWeb.Migrations
{
    [DbContext(typeof(StoreDbContext))]
    [Migration("20240620021323_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("StoreAppWeb.Concreate.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Telefon",
                            Description = "Harika bir cihaz",
                            Name = "Iphone 15 Plus",
                            Price = 62000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Telefon",
                            Description = "Harika bir cihaz",
                            Name = "Iphone 15",
                            Price = 50000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Telefon",
                            Description = "Harika bir cihaz",
                            Name = "Iphone 15 Pro Max",
                            Price = 90000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Telefon",
                            Description = "Harika bir cihaz",
                            Name = "Iphone 15 Pro",
                            Price = 80000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Telefon",
                            Description = "Harika bir cihaz",
                            Name = "Iphone 14 Pro Max",
                            Price = 60000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Telefon",
                            Description = "Harika bir cihaz",
                            Name = "Iphone 14 Pro",
                            Price = 55000m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
